excerpt_separator: ""
pygments: true
markdown: kramdown
highlighter: rouge
url: http://mattfedd.github.io
title: mattfedd
tagline: A log of everyday life
description: My awesome new site
paginate: 5
