excerpt_separator: ""
pygments: true
markdown: kramdown
highlighter: rouge
url: http://mattfedd.github.io
title: mattfedd
tagline: Home
description: Travel notes, research updates, and other shenanigans
paginate: 3
paginate_path: "blog/page:num/"
version: "1.0.0"
